### ISSUE TITLE
Creating a user through sample is failing with tooManyRetries

### ISSUE THREAD

**Issue by chris-skuvault** [Azure-Samples/ms-identity-dotnetcore-b2c-account-management#6]
When using this library to create a user with custom attributes I started running into issues where the create user functionality seems to have broken. It worked the other day when I tried it but now I keep getting exceptions on the AddAsync call from the graph client when creating user with custom attributes. Yesterday it worked and created the user and today the exception I'm getting is 

Code: tooManyRetries
Message: More than 3 retries encountered while sending the request.

Here is stack
`at Microsoft.Graph.HttpProvider.<SendRequestAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__31`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at b2c_ms_graph.UserService.<CreateUserWithCustomAttribute>d__7.MoveNext() in C:\Git\ms-identity-dotnetcore-b2c-account-management\src\Services\UserService.cs:line 277`

In azure b2c tenant in the audit logs I see Name : MethodExecutionResult.
New Value : "Microsoft.Online.DirectoryServices.DirectoryServiceUnavailableException" for what looks like what might be the issue. Does this indicate that Microsoft graph api endpoint is having issues at the moment? 

It is reproducible with code provided in this repo by just running the console setting up all the keys and then typing 7 while the console is running to have it create a user with custom attributes.

**Comment by chris-skuvault** [comment]
Well trying this morning it seems to be resolved. Guess it was just an intermittent outage.
